Build failure after merge of the drm-intel tree
After merging the drm-intel tree into -next an x86 allmodconfig build fails
with:

In file included from include/linux/kobject.h:29:0,
                 from include/linux/cpufreq.h:16,
                 from drivers/gpu/drm/i915/intel_pm.c:28:
drivers/gpu/drm/i915/intel_pm.c: In function ‘intel_pm_init’:
drivers/gpu/drm/i915/intel_pm.c:5883:34: error: ‘struct intel_gen6_power_mgmt’ has no member named ‘vlv_work’
  INIT_DELAYED_WORK(&dev_priv->rps.vlv_work, vlv_rps_timer_work);
                                  ^
include/linux/workqueue.h:216:16: note: in definition of macro ‘__INIT_WORK’
   __init_work((_work), _onstack);    \
                ^
include/linux/workqueue.h:244:3: note: in expansion of macro ‘INIT_WORK’
   INIT_WORK(&(_work)->work, (_func));   \
   ^
include/linux/workqueue.h:260:2: note: in expansion of macro ‘__INIT_DELAYED_WORK’
  __INIT_DELAYED_WORK(_work, _func, 0)
  ^
drivers/gpu/drm/i915/intel_pm.c:5883:2: note: in expansion of macro ‘INIT_DELAYED_WORK’
  INIT_DELAYED_WORK(&dev_priv->rps.vlv_work, vlv_rps_timer_work);
  ^
drivers/gpu/drm/i915/intel_pm.c:5883:34: error: ‘struct intel_gen6_power_mgmt’ has no member named ‘vlv_work’
  INIT_DELAYED_WORK(&dev_priv->rps.vlv_work, vlv_rps_timer_work);
                                  ^
and so on caused by 671952a2a290a (drm/i915: fix rps.vlv_work
initialization) in the drm-intel-fixes tree interacting with ac3a48b3036
(drm/i915: Boost RPS frequency for CPU stalls) from the drm-intel tree.

I have used the fix below for today:

From 4f4dccef92d64393e2a7e867f7c2755c09178c48 Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@linaro.org>
Date: Thu, 3 Oct 2013 18:10:55 +0100
Subject: [PATCH] drm/i915: Resolve interaction with drm-fixes tree

Signed-off-by: Mark Brown <broonie@linaro.org>
Signed-off-by: Thierry Reding <treding@nvidia.com>